services:
  - type: web
    name: picgen-backend
    env: docker
    region: virginia      
    branch: main          
    rootDirectory: picgen_server/demo
    plan: free
    envVars:
      - key: DB_URL
        fromSecret: true # store as a Render secret
      - key: DB_USERNAME
        fromSecret: true
      - key: DB_PASSWORD
        fromSecret: true   
      - key: JWT_SECRET_KEY
        fromSecret: true   
      - key: IMGBB_KEY
        fromSecret: true   
